### PR TITLE
ToC items addition & update

### PR DESCRIPTION
**Pull request by nzjohnah**
Put all items on ToC from Google Doc. Not sure if I'm doing it right but the ToC link doesn't seems to work on my FireFox browser.

### CODE REVIEW

**Comment by RaySingerNZ** [comment]
Hey @nzjohnah, thanks for doing that. It's good to keep ticking away at this. 

@nevercast's latest commit has working links. You can see his code [here](https://raw.githubusercontent.com/MorphicDev/TrackToLearnCSharp/master/TrackToLearnCSharp.md).

He used the syntax where this:
[2.2 Consume Types](#22-consume-types)

Goes to:
## 2.2 Consume Types

Rather than closing your PR could you edit your file here on GitHub and add the working links? I'll merge when done.

Cheers,

**Comment by nevercast** [comment]
@nzjohnah You can push another commit to your master branch for amendments also. 
I would suggest trying to PR some feature branches to yourself or another repo in practice as I see you are PRing from master again.

**Comment by nzjohnah** [comment]
Ok I will do that, sorry about the stuff up.

Regard,
John

**Comment by nevercast** [comment]
It's not hassle to us, just makes your life harder.

**Pull request closed without merging**
